//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paczki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurierzy
    {
        public int Id { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public Nullable<int> Wiek { get; set; }
        public Nullable<int> Pensja { get; set; }
        public string Numer_telefonu { get; set; }
    }
}
