//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paczki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przesylki
    {
        public int Id { get; set; }
        public string Typ_przesylki { get; set; }
        public string Nazwa { get; set; }
        public string Metoda_przeslania { get; set; }
        public string Waga { get; set; }
        public string Nadawca { get; set; }
        public string Odbiorca { get; set; }
        public string Data_nadania { get; set; }
        public string Status { get; set; }
    }
}
